### PR TITLE
MON-3257: Sync with upstream master

### PR DESCRIPTION
**Pull request by slashpai**
Since this repo was way too told more things to update before merging, not creating as draft to see how CI is on this repo now

Did following steps soo far
`git rm -r .` to delete all files in fork for cleanup
`git pull upstream master` to sync with upstream
Updated OWNERS in charts folder

cc: @simonpasquier 

Add ocp dockerfile and ci-operator file https://github.com/openshift/kubernetes-metrics-server/pull/10
release PR: https://github.com/openshift/release/pull/40893

### CODE REVIEW

**Comment by slashpai** [comment]
https://github.com/openshift/kubernetes-metrics-server/pull/9 created first to update OWNERS file

**Comment by simonpasquier** [comment]
It looks like the LICENSE file is missing. Can also run `go mod vendor` and commit the vendor/ directory?

**Comment by slashpai** [comment]
> It looks like the LICENSE file is missing. Can also run `go mod vendor` and commit the vendor/ directory?

not sure how LICENSE file went missing but I have cherry-picked from upstream now. Also added vendor
@simonpasquier can you review again?

**Pull request merged**
