### PR TITLE
[release-4.17]: OCPBUGS-46491: Disable HTTP2

### PR DESCRIPTION
**Pull request by slashpai**
cc: @machine424 @jan--f @juzhao

### CODE REVIEW

**Comment by machine424** [comment]
Thanks for this.
/lgtm
/hold
It'd be helpful for testing to have the CMO PR that enables the toggle

**Comment by slashpai** [comment]
The test failures looks to be issue with CI cluster, I couldn't find issue related to change

@machine424 I was wondering should we expose the flag or is it better to set `serverConfig.SecureServing.DisableHTTP2 = true` as we want it to be true always, wdyt?

**Comment by machine424** [comment]
> @machine424 I was wondering should we expose the flag or is it better to set `serverConfig.SecureServing.DisableHTTP2 = true` as we want it to be true always, wdyt?

That would provide a simpler "kill switch", even though it would require to run CMO in unmanaged mode, also it makes it more explicit that http2 is disabled. If it's simple, let's go for it.

**Comment by slashpai** [comment]
> > @machine424 I was wondering should we expose the flag or is it better to set `serverConfig.SecureServing.DisableHTTP2 = true` as we want it to be true always, wdyt?
> 
> That would provide a simpler "kill switch", even though it would require to run CMO in unmanaged mode, also it makes it more explicit that http2 is disabled. If it's simple, let's go for it.

Had a chat with @dgrisonnet, he suggested to hardcore `serverConfig.SecureServing.DisableHTTP2 = true` to avoid someone changing it.

May be we can keep the change simple here by explicitly stating its being disabled.

**Comment by dgrisonnet** [comment]
Since this is a patch to fix a CVE, I think going with an hardcoded version is better as it prevents users to open themselves to a CVE without knowing.
In 4.18+ we will have a flag because we get it from upstream and it avoids having to maintain a carry-patch, but I think for the backports here it should be better to go with the hadcoded version. It also avoid having to backport changes in CMO.

**Comment by machine424** [comment]
Your call ;)

**Comment by slashpai** [comment]
cc @jan--f for backport approval
@juzhao for cherry pick approval

**Comment by machine424** [comment]
You're making me take the fall :)
/lgtm
@juzhao, please tell me this is not working haha

**Pull request merged**
