### PR TITLE
MON-3523: Disable HTTP2

### PR DESCRIPTION
**Pull request by slashpai**
Till upstream fix is done

cc: @simonpasquier @dgrisonnet

### CODE REVIEW

**Comment by simonpasquier** [comment]
/hold
there's no rush in merging it downstream and I'd rather wait for the upstream fix to land.

**Comment by dgrisonnet** [comment]
@simonpasquier the upstream fix will most likely need to be in the kube-apiserver library so if we follow that route, it won't land until k8s 1.30 which should be either OCP 4.16 or 4.17

**Comment by dgrisonnet** [comment]
This PR looks good to me, leaving the decision up to @simonpasquier

**Pull request closed without merging**
