### PR TITLE
Bug 1780302: metrics/storage/podmetrics: ignore evicted pods

### PR DESCRIPTION
**Pull request by s-urbaniak**
This is a backport of https://github.com/kubernetes-sigs/metrics-server/commit/0bf0c02b82bb236e8d6f145923a013f641f58b3e

/cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by sdodson** [comment]
I think you need to reach out to DPTP, the bot shouldn't be rejecting this so it needs to be configured for this repo and branch. They can point you in the right direction for the config files that need to be updated.

**Comment by paulfantom** [comment]
It seems that repository is lacking OWNERS file and as such prow bot cannot assign `approved` label, which in turn prevents tide from merging this PR.

**Pull request merged**
