### PR TITLE
Rebase to latest metrics-server and fix up OWNERs

### PR DESCRIPTION
**Pull request by DirectXMan12**
The rebases to the shiny new metrics-server refactor, and fixes the upstream OWNERS file to just contain Red Hatters for the fork.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
cc @brancz

**Comment by DirectXMan12** [comment]
@smarterclayton what's the process for this?  We probably need to branch for 3.11.  Presumably we then need to directly push to actually commit the rebase?  I don't have write permissions to this repo (nor do I actually know the concrete process)...

**Comment by smarterclayton** [comment]
You don't rebase, you do "git merge upstream/master" or whatever.

Then we merge the PR.

Branching for 3.11 happens centrally.

**Comment by DirectXMan12** [comment]
ack

**Pull request closed without merging**
